version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    # 生产环境的基础配置
    environment:
      - NODE_ENV=production
    env_file:
      - .env
